proforms/first_app/urls.py
from django.urls import path,include
from first_app import views


app_name = 'first_app'

urlpatterns = [
    #path('',views.index,name="index" ),
    path('relative/',views.relative,name="relative" ),
    path('users/',views.users,name="users" ),
    path('other/',views.other,name="other" ),
    
]

proforms/proforms/urls.py
from django.contrib import admin
from django.urls import path,include
from first_app import views

urlpatterns = [
    path('',views.index, name="index"),
    path('first_app/',include('first_app.urls')),
    path('admin/', admin.site.urls),
    
]

proforms/first_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254, unique=True)

proforms/first_app/forms.py
from django import forms
from first_app.models import User

class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

proforms/first_app/views.py
from django.shortcuts import render
from first_app.forms import NewUserForm
# Create your views here.
def index(request):
    return render(request,'first_app/index.html')

def other(request):
    return render(request,'first_app/other.html')


def users(request):
    form = NewUserForm()

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Error! Form Invalid")

    return render(request,'first_app/users.html',{'form':form})


def relative(request):
    return render(request,'first_app/relative_url.html')

proforms/first_app/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MYsite</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="navbar-brand" href="{% url 'index' %}">>DJANGO</a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMin</a>
            <a class="nav-item nav-link" href="{% url 'first_app:other' %}">Other</a>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        
        {% endblock %}
    </div>
</body>
</html>

proforms/first_app/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
    <h1>This the INDEX</h1>
    <h2>seuhfuieyufhseuifyieshfhjerufyhsufguysy9fhreof</h2>
    {% endblock %}
    

proforms/first_app/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
    <h1>THIS is OTHER</h1>
    <h2>TTKSHFUKYIYHFUxfguighsufvbsuih</h2>
    {% endblock %}

proforms/first_app/templates/first_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Relative url</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'first_app:other' %}">Link to the other page</a>
    
    <a href="{% url 'first_app:users' %}">SIGN UP HERE</a>
</body>
</html>

proforms/first_app/templates/first_app/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users</title>
</head>
<body>
    <h1>This is the users page for some reason</h1>
    <div class="container">
        <h2>Fill this form</h2>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>